In [1]:
##  Linear regression with multiple variable
## Polynomial regression

* +ve Linear relation
    - input and output have increased vice versa
* -ve Linear relation
    - input and output have decreased vice versa
### Polynomial regeression formula
 - y=ax^2+bx+c(for degree 2)
 - y=ax^3+bx^2+cx+1 (if degree 2)

##### Linear regeression with multiple variables
- input more than 1 features
- output single target
#### Steps for ML:
- Read data or get data
- Data Preprocessing or data wrangling
- Sperate the our input data and output data
- Apply or train the model
- Test the model
- Evalution matrices (score) for the model

In [2]:
# import required packages:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Read the data
head_df=pd.read_csv("https://raw.githubusercontent.com/AP-State-Skill-Development-Corporation/Datasets/master/Regression/headbrain.csv")
head_df.head()

Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0       1          1             4512                 1530
1       1          1             3738                 1297
2       1          1             4261                 1335
3       1          1             3777                 1282
4       1          1             4177                 1590

In [6]:
head_df.columns

Index(['Gender', 'Age Range', 'Head Size(cm^3)', 'Brain Weight(grams)'], dtype='object')

In [7]:
head_df.Gender.unique()

array([1, 2], dtype=int64)

In [8]:
head_df['Gender'].value_counts()

1    134
2    103
Name: Gender, dtype: int64

In [9]:
head_df.info

<bound method DataFrame.info of      Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0         1          1             4512                 1530
1         1          1             3738                 1297
2         1          1             4261                 1335
3         1          1             3777                 1282
4         1          1             4177                 1590
..      ...        ...              ...                  ...
232       2          2             3214                 1110
233       2          2             3394                 1215
234       2          2             3233                 1104
235       2          2             3352                 1170
236       2          2             3391                 1120

[237 rows x 4 columns]>

In [10]:
head_df.describe()

Gender   Age Range  Head Size(cm^3)  Brain Weight(grams)
count  237.000000  237.000000       237.000000           237.000000
mean     1.434599    1.535865      3633.991561          1282.873418
std      0.496753    0.499768       365.261422           120.340446
min      1.000000    1.000000      2720.000000           955.000000
25%      1.000000    1.000000      3389.000000          1207.000000
50%      1.000000    2.000000      3614.000000          1280.000000
75%      2.000000    2.000000      3876.000000          1350.000000
max      2.000000    2.000000      4747.000000          1635.000000

In [12]:
input_data=head_df.drop("Brain Weight(grams)",axis=1)
output_data=head_df["Brain Weight(grams)"]

In [15]:
input_data.columns


Index(['Gender', 'Age Range', 'Head Size(cm^3)'], dtype='object')

In [18]:
# Applying the model
from sklearn.linear_model import LinearRegression
linear=LinearRegression()

In [20]:
# Train the model by using fit method
linear.fit(input_data,output_data)

LinearRegression()

In [24]:
pred=linear.predict(input_data)
pred

array([1519.93452386, 1330.91463003, 1458.63737483, 1340.43888825,
       1438.1235879 , 1293.55023241, 1342.39258224, 1287.20072693,
       1300.38816139, 1390.50229682, 1258.87216403, 1393.18862606,
       1306.98187861, 1445.69415212, 1353.87053445, 1364.61585141,
       1272.05959849, 1264.48903426, 1173.88647533, 1498.44388994,
       1365.10427491, 1406.13184876, 1347.03260547, 1324.07670105,
       1577.32428491, 1498.19967819, 1403.68973127, 1400.27076679,
       1261.55849328, 1437.6351644 , 1342.88100574, 1345.07891148,
       1420.05191847, 1434.21619992, 1433.48356467, 1349.47472296,
       1279.38595096, 1333.35674752, 1232.25308338, 1270.83853974,
       1385.61806184, 1274.01329248, 1471.82480928, 1347.03260547,
       1361.44109867, 1403.20130777, 1470.11532704, 1190.98129777,
       1307.22609036, 1307.95872561, 1368.27902765, 1344.34627623,
       1460.83528057, 1410.2834485 , 1397.82864929, 1262.53534027,
       1368.0348159 , 1411.46881323, 1355.05589918, 1290.09557

In [26]:
linear.score(input_data,output_data)*100

65.28346387526653

In [30]:
linear.predict([[1,2,5000]])

array([1615.14141201])

In [31]:
linear.predict([[1,1,4512]])

array([1519.93452386])

In [33]:
linear.coef_

array([-22.5432537 , -23.96844543,   0.24421175])

In [34]:
linear.intercept_


464.5628108859038