In [1]:
# over fitting under fitting
## over fitting 
#### bias is a simplifying the assumptions made by the model to make target functions easier to approximate
#### variance is the amount that the estimate of the target functions will change the given different traning data.

##### Over fitting
* when ever you have low bias and high variance
* Good performance on the training data poor generalization to other(test) data
##### under fitting
* Poor performance on the traing data and poor generalization to other data(test data)
* when ever you have high bias and low variance

###### L1 regression -->MSE = (1/n) * Σ(actual – prediction)2
where:
- Σ – a fancy symbol that means “sum”
- n – sample size
- actual – the actual data value
- prediction – the predicted data value



In [3]:
###### Ridge regression adds " square magnitude " of coefficient penalty term to the loss functions
###### Lasso regression(Least Absolute Shrinkage and Selection Operator):It is used over regression methods for a more accurate prediction. This model uses shrinkage. Shrinkage is where data values are shrunk towards a central point as the mean.

In [5]:
######### Prevention of over fitting and under fitting
# Cross Validation: Cross validation is a powerful prevention measure against overfiting
# train with more datar 
# remote features
# EArly stopping
# Regulization 
# Ensembling

In [6]:
# import required packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
m=100
x=np.random.rand(m,1)
y=0.5*x**2+x+2+np.random.randn(m,1) ### equation as ax^2+bx+c

In [14]:
print(x,"x values")
print(y,"y values")
print(m)

[[0.88333617]
 [0.14801718]
 [0.27304976]
 [0.00152951]
 [0.22734537]
 [0.6898812 ]
 [0.86647918]
 [0.54852902]
 [0.22491819]
 [0.19335605]
 [0.49816756]
 [0.81089636]
 [0.72070019]
 [0.3681455 ]
 [0.12730351]
 [0.93319038]
 [0.2007224 ]
 [0.89763843]
 [0.06247831]
 [0.21681104]
 [0.1173065 ]
 [0.47167514]
 [0.37187984]
 [0.6862416 ]
 [0.22036599]
 [0.84960905]
 [0.12751896]
 [0.33744304]
 [0.29077681]
 [0.14501429]
 [0.13901321]
 [0.74519352]
 [0.47160201]
 [0.77790254]
 [0.59998655]
 [0.99431803]
 [0.01351298]
 [0.22613127]
 [0.8807048 ]
 [0.39548474]
 [0.20689839]
 [0.80955272]
 [0.59516596]
 [0.32002649]
 [0.29879988]
 [0.03636388]
 [0.69362543]
 [0.40439096]
 [0.56204919]
 [0.31576149]
 [0.41414888]
 [0.60762842]
 [0.0234633 ]
 [0.14828441]
 [0.27579221]
 [0.50671716]
 [0.06835256]
 [0.25994515]
 [0.45066634]
 [0.36004107]
 [0.74347114]
 [0.91855977]
 [0.68647083]
 [0.88275465]
 [0.84600002]
 [0.49489608]
 [0.87326748]
 [0.89928303]
 [0.74230499]
 [0.78954525]
 [0.13615698]
 [0.23

In [16]:
x.shape

(100, 1)

In [17]:
from sklearn.linear_model import Ridge
rd=Ridge()

In [18]:
x[1]

array([0.14801718])

In [19]:
np.ndim(x)

2

In [20]:
# fit the model
rd.fit(x,y)

Ridge()

In [21]:
rd.predict(x[[1]])

array([[2.20157759]])

In [25]:
from sklearn import datasets

In [37]:
data=datasets.load_boston()
data.keys()


dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [42]:
df=pd.DataFrame(data.data,columns = data.feature_names)
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [44]:
df.shape

(506, 13)

In [45]:
data.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [46]:
df['LandPrice']=data.target

In [48]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  LandPrice  
0     15.3  396.90   4.98       24.0  
1     17.8  396.90   9.14       21.6  
2     17.8  392.83   4.03       34.7  
3     18.7  394.63   2.94       33.4  
4     18.7  396.90   5.33       36.2

In [58]:
df.isnull().sum()

CRIM         0
ZN           0
INDUS        0
CHAS         0
NOX          0
RM           0
AGE          0
DIS          0
RAD          0
TAX          0
PTRATIO      0
B            0
LSTAT        0
LandPrice    0
dtype: int64

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   CRIM       506 non-null    float64
 1   ZN         506 non-null    float64
 2   INDUS      506 non-null    float64
 3   CHAS       506 non-null    float64
 4   NOX        506 non-null    float64
 5   RM         506 non-null    float64
 6   AGE        506 non-null    float64
 7   DIS        506 non-null    float64
 8   RAD        506 non-null    float64
 9   TAX        506 non-null    float64
 10  PTRATIO    506 non-null    float64
 11  B          506 non-null    float64
 12  LSTAT      506 non-null    float64
 13  LandPrice  506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB


In [60]:
df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT   LandPrice  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [75]:
# seperate the input and target features
x = df.iloc[:,0:-1]
x.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [79]:
y=df["LandPrice"]
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: LandPrice, Length: 506, dtype: float64

In [80]:
from sklearn.linear_model import LinearRegression
lin_alg=LinearRegression()

In [83]:
# train the model using fit
lin_alg.fit(x,y)

LinearRegression()

In [92]:
#split the data into training data and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [96]:
print("LR train score",lin_alg.score(x_train,y_train))

LR train score 0.7470310386818004


In [98]:
print("LR test score",lin_alg.score(x_test,y_test))

LR test score 0.7225427185572685
