In [1]:
import numpy as np

In [2]:
a = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[2,4,5]]])

In [3]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [ 2,  4,  5]]])

In [4]:
a[1,0,0]

8

In [5]:
#boolean index
names = np.array(["a","b","c","a","c"])
data = np.random.rand(5,3)

In [6]:
names

array(['a', 'b', 'c', 'a', 'c'], dtype='<U1')

In [7]:
data

array([[0.73614655, 0.76018353, 0.29939682],
       [0.51823105, 0.94871102, 0.60506827],
       [0.52543276, 0.78297552, 0.27557844],
       [0.47459856, 0.71351299, 0.34162424],
       [0.04900402, 0.83348343, 0.48962949]])

In [8]:
names == "a"

array([ True, False, False,  True, False])

In [9]:
data[names == "a"]

array([[0.73614655, 0.76018353, 0.29939682],
       [0.47459856, 0.71351299, 0.34162424]])

In [10]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [ 2,  4,  5]]])

In [11]:
print(a>=4)

[[[False False False]
  [ True  True  True]]

 [[ True  True  True]
  [False  True  True]]]


In [12]:
a[a>=4]

array([ 4,  5,  6,  8,  9, 10,  4,  5])

In [13]:
a[a%2==0]

array([ 2,  4,  6,  8, 10,  2,  4])

In [14]:
a%2==0

array([[[False,  True, False],
        [ True, False,  True]],

       [[ True, False,  True],
        [ True,  True, False]]])

In [15]:
a[(a>2) & (a<7)]

array([3, 4, 5, 6, 4, 5])

In [16]:
a[(a>2) and (a>7)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
a[(a>2) | (a<7)]


- Using generators
- fromiter(iterable,datatype)

In [ ]:
a1 = (i*i for i in range(5) for j in range(10) if j<i)
np.fromiter(a1,float)

In [ ]:
for i in range(5):#0,1,2,3
    for j in range(10):#0
        if j<i:#0<2,1<2,2<2
            print(i*i)#1*1

In [ ]:
a2 = np.array([1,2,3,8,90,2,34,5,1])
a2

In [ ]:
np.where(a2<5)

In [ ]:
a2[a2<5]

In [ ]:
a2[np.where(a2<5)]

In [ ]:
np.nonzero(a2<5)

In [ ]:
a2[np.nonzero(a2<5)]

- Statistical and aggregate functions

In [68]:
arr = np.array([[10,20,30],[23,45,12]])
arr1 = np.array([[23,12,56],[89,45,67]])

In [69]:
print(arr)
print(arr1)

[[10 20 30]
 [23 45 12]]
[[23 12 56]
 [89 45 67]]


In [70]:
print(arr.sum())

140


In [71]:
print(arr1.sum())

292


In [72]:
print(arr.sum(axis=0))

[33 65 42]


In [73]:
arr

array([[10, 20, 30],
       [23, 45, 12]])

In [74]:
print(arr.sum(axis=1))

[60 80]


In [75]:
print(arr.sum(0))

[33 65 42]


In [76]:
arr.sum(1)

array([60, 80])

In [77]:
np.average(arr)

23.333333333333332

In [78]:
np.average(arr,axis=1)

array([20.        , 26.66666667])

In [79]:
np.prod(arr1,dtype=float)

4147385760.0

In [80]:
help(np.prod)

Help on function prod in module numpy.core.fromnumeric:

prod(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)
    Return the product of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a product is performed.  The default,
        axis=None, will calculate the product of all the elements in the
        input array. If axis is negative it counts from the last to the
        first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a product is performed on all of the
        axes specified in the tuple instead of a single axis or all the
        axes as before.
    dtype : dtype, optional
        The type of the returned array, as well as of the accumulator in
        which the elements are multiplied.  The dtype of `a` is used by
        default unless `a` has an integer dtype of les

In [81]:
arr1

array([[23, 12, 56],
       [89, 45, 67]])

In [82]:
23*12*56*89*45*67

4147385760

In [83]:
np.prod(arr1,dtype=float) 

4147385760.0

In [84]:
np.prod(arr,0)

array([230, 900, 360])

In [85]:
arr.min()

10

In [86]:
arr1.min()

12

In [87]:
arr.min(axis=0)

array([10, 20, 12])

In [88]:
arr.min(1)

array([10, 12])

In [89]:
arr.max()

45

In [90]:
arr.max(1)

array([30, 45])

In [91]:
arr.mean()

23.333333333333332

In [92]:
arr.mean(0)

array([16.5, 32.5, 21. ])

In [93]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [ ]:
np.median(arr)

In [94]:
np.median(arr,1)

array([20., 23.])

In [95]:
#variance = (element1-mean)^2+----+(elementN-mean)^2
arr.var()

138.55555555555557

In [96]:
arr.var(0)

array([ 42.25, 156.25,  81.  ])

In [97]:
#standarad deviation---square root of variance
arr.std()

11.77096238867305

In [98]:
arr.std(0)

array([ 6.5, 12.5,  9. ])

In [99]:
#cumulative sum
arr.cumsum()

array([ 10,  30,  60,  83, 128, 140], dtype=int32)

In [100]:
arr

array([[10, 20, 30],
       [23, 45, 12]])

In [101]:
arr.cumsum(1)

array([[10, 30, 60],
       [23, 68, 80]], dtype=int32)

In [102]:
arr.cumprod()

array([      10,      200,     6000,   138000,  6210000, 74520000],
      dtype=int32)

In [103]:
arr

array([[10, 20, 30],
       [23, 45, 12]])

In [104]:
arr.cumprod(0)

array([[ 10,  20,  30],
       [230, 900, 360]], dtype=int32)

In [105]:
arr

array([[10, 20, 30],
       [23, 45, 12]])

In [106]:
arr.argmin()

0

In [107]:
arr.min()

10

In [108]:
arr.argmax()

4

In [109]:
arr.argmax(0)

array([1, 1, 0], dtype=int64)

In [110]:
np.corrcoef(arr)

array([[ 1.        , -0.32732684],
       [-0.32732684,  1.        ]])

### Saving data

In [111]:
data = np.linspace(0,100,200)
data

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

In [112]:
np.savetxt("file1.dt",data)

In [113]:
np.loadtxt("file1.dt")

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

In [114]:
#10
bin(10)

'0b1010'

In [115]:
hex(10)

'0xa'

In [116]:
oct(10)

'0o12'

### Pandas

- Pandas ia also one of the library in python which is used to perform data analysis and manipulation

- Data analysis--->cleaning,processing,modeling and inspecting the data

- Data Manipulation-->adding,deleting,modifications

- reduce the complexity and make our works easier rate.

- create the data in 2types:
    - Series
    - DataFrame

In [52]:
import pandas as pd

In [53]:
# list
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [54]:
#creating a series by using an array
a = pd.Series(np.array([5,23,45,67,23]))

In [55]:
a

0     5
1    23
2    45
3    67
4    23
dtype: int32

In [56]:
#dictionary
d = {"a":1,"b":2}
pd.Series(d)

a    1
b    2
dtype: int64

In [57]:
a=pd.DataFrame({"roll":[1,2,3],"Name":["Nandu","Sanjay","Karthik"]})
a


Name  roll
0    Nandu     1
1   Sanjay     2
2  Karthik     3

In [58]:
pd.Series([1,2,3],index=["a","b","c"])

a    1
b    2
c    3
dtype: int64

In [59]:
d={"roll":[1,2,3],"Name":["Nandu","Sanjay","Karthik"]}
print(pd.Series(d))
     

Name    [Nandu, Sanjay, Karthik]
roll                   [1, 2, 3]
dtype: object


In [60]:
import shutil, os
f="file1.dat"
d ="fol"
shutil.move(f, d)

FileNotFoundError: [Errno 2] No such file or directory: 'file1.dat'