### Numpy

- Numerical python popularly known as numpy.Numpy is designed to carry out mathematical computations at a faster and easier rate.

- In command line
    - pip install numpy

In [5]:
pip install numpy


The following command must be run outside of the IPython shell:

    $ pip install numpy

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more informations on how to install packages:

    https://docs.python.org/3/installing/


In [6]:
import numpy as np

In [7]:
np.__version__

'1.14.0'

- 1D - array
- 2D - array
- 3D - array

In [8]:
a = np.array([1,2,3])

In [9]:
a

array([1, 2, 3])

In [10]:
a.ndim

1

In [11]:
a.dtype

dtype('int32')

In [12]:
b = np.array([1,2,3],float)
b.dtype

dtype('float64')

In [13]:
c = np.array([1,2.3,"apssdc"])
c

array(['1', '2.3', 'apssdc'], dtype='<U32')

In [14]:
c.dtype

dtype('<U32')

In [15]:
d = np.array([1,2.3,2])
d.dtype

dtype('float64')

In [16]:
e = np.array("06-10-2020")
e.dtype

dtype('<U10')

In [17]:
s = np.array(2+7j)
s.dtype

dtype('complex128')

In [18]:
range(1,10)

range(1, 10)

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
range(1,10,2)

range(1, 10, 2)


In [103]:
a = np.arange(1,10,0.2)
a

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [22]:
a.size 

45

In [23]:
a.shape

(45,)

In [24]:
f = np.arange(1,51)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [25]:
f.reshape(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [26]:
f.reshape(10,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [27]:
f.reshape(2,-1) # 2,25 or 25,2 or 5,10 or 10,5

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [28]:
f.reshape(-1,25)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [29]:
f.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [30]:
a = np.arange(1,50)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [31]:
a1 = a.reshape(7,7)
a1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [32]:
a.reshape(8,-1)

ValueError: cannot reshape array of size 49 into shape (8,newaxis)

In [33]:
a1.ndim

2

In [34]:
np.array((1,2,3))

array([1, 2, 3])

In [35]:
np.array({1:2})

array({1: 2}, dtype=object)

In [36]:
arr = np.arange(1,51).reshape(5,1,10)
arr

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35, 36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45, 46, 47, 48, 49, 50]]])

In [37]:
arr.ndim

3

In [38]:
arr.shape

(5, 1, 10)

In [39]:
arr.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [40]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
import numpy as np
a =np.array([[[1,2,3],[4,5,6],[1,2,10],[4,5,6]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 1,  2, 10],
        [ 4,  5,  6]]])

In [98]:
np.linspace(1,10,200) # start,ending,parts

array([ 1.        ,  1.04522613,  1.09045226,  1.13567839,  1.18090452,
        1.22613065,  1.27135678,  1.31658291,  1.36180905,  1.40703518,
        1.45226131,  1.49748744,  1.54271357,  1.5879397 ,  1.63316583,
        1.67839196,  1.72361809,  1.76884422,  1.81407035,  1.85929648,
        1.90452261,  1.94974874,  1.99497487,  2.04020101,  2.08542714,
        2.13065327,  2.1758794 ,  2.22110553,  2.26633166,  2.31155779,
        2.35678392,  2.40201005,  2.44723618,  2.49246231,  2.53768844,
        2.58291457,  2.6281407 ,  2.67336683,  2.71859296,  2.7638191 ,
        2.80904523,  2.85427136,  2.89949749,  2.94472362,  2.98994975,
        3.03517588,  3.08040201,  3.12562814,  3.17085427,  3.2160804 ,
        3.26130653,  3.30653266,  3.35175879,  3.39698492,  3.44221106,
        3.48743719,  3.53266332,  3.57788945,  3.62311558,  3.66834171,
        3.71356784,  3.75879397,  3.8040201 ,  3.84924623,  3.89447236,
        3.93969849,  3.98492462,  4.03015075,  4.07537688,  4.12

In [108]:
a1 = a.flatten()
a1

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [109]:
np.tile(10,[5,5])

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [44]:
np.ones((10,2),dtype = int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [105]:
np.ones((3,2,2),dtype = int)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [107]:
np.zeros((2,3,1),object)

array([[[0],
        [0],
        [0]],

       [[0],
        [0],
        [0]]], dtype=object)

In [47]:
np.eye(4,3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

#### Sorting

In [48]:
arr1 = np.array([2,34,12,67,23,90,78])
arr1

array([ 2, 34, 12, 67, 23, 90, 78])

In [49]:
np.sort(arr1)

array([ 2, 12, 23, 34, 67, 78, 90])

In [50]:
places = ("vijayawada","tirupathi","kalahasthri")
temples = ("durgama","tirumala","shiva")
a = np.lexsort((temples,places))
a

array([2, 1, 0], dtype=int64)

In [51]:
[places[i]+" "+temples[i] for i in a]

['kalahasthri shiva', 'tirupathi tirumala', 'vijayawada durgama']

#### Indexing

In [52]:
d = np.arange(1,100,2)
d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [53]:
d[6]

13

In [54]:
d[2:10]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [55]:
arr2 = np.arange(1,51).reshape(5,10)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [56]:
arr2[2,2]

23

In [57]:
arr2[3,7]

38

In [58]:
arr2[2:3,2:3]

array([[23]])

In [59]:
arr2 = np.arange(1,51).reshape(5,1,10)
arr2

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]],

       [[31, 32, 33, 34, 35, 36, 37, 38, 39, 40]],

       [[41, 42, 43, 44, 45, 46, 47, 48, 49, 50]]])

In [60]:
#how acces the particular element in 3d

In [61]:
# concatenate
a = np.array([[2,3],[7,8]])
b = np.array([[6,3],[8,12]])
a

array([[2, 3],
       [7, 8]])

In [62]:
b

array([[ 6,  3],
       [ 8, 12]])

In [63]:
np.concatenate((a,b))

array([[ 2,  3],
       [ 7,  8],
       [ 6,  3],
       [ 8, 12]])

In [64]:
np.concatenate((a,b),axis=1) # axis=1--columns,axis-0---rows

array([[ 2,  3,  6,  3],
       [ 7,  8,  8, 12]])

In [65]:
np.vstack((a,b))

array([[ 2,  3],
       [ 7,  8],
       [ 6,  3],
       [ 8, 12]])

In [66]:
np.hstack((a,b))

array([[ 2,  3,  6,  3],
       [ 7,  8,  8, 12]])

In [67]:
a

array([[2, 3],
       [7, 8]])

In [68]:
# transpose
a.T

array([[2, 7],
       [3, 8]])

In [69]:
a.swapaxes(0,1)

array([[2, 7],
       [3, 8]])

### Math
- Arithmetic functions

In [70]:
a

array([[2, 3],
       [7, 8]])

In [71]:
b

array([[ 6,  3],
       [ 8, 12]])

In [72]:
print(a+b)

[[ 8  6]
 [15 20]]


In [73]:
print(a-b)

[[-4  0]
 [-1 -4]]


In [74]:
print(a%b)

[[2 0]
 [7 8]]


In [75]:
print(a//b)

[[0 1]
 [0 0]]


In [76]:
print(a/b)

[[0.33333333 1.        ]
 [0.875      0.66666667]]


In [77]:
np.divide(a,b)

array([[0.33333333, 1.        ],
       [0.875     , 0.66666667]])

In [78]:
np.divmod(a,b)

(array([[0, 1],
        [0, 0]], dtype=int32), array([[2, 0],
        [7, 8]], dtype=int32))

In [79]:
a%b

array([[2, 0],
       [7, 8]], dtype=int32)

In [80]:
np.floor_divide(a,b)

array([[0, 1],
       [0, 0]], dtype=int32)

In [81]:
a//b

array([[0, 1],
       [0, 0]], dtype=int32)

In [82]:
a

array([[2, 3],
       [7, 8]])

In [83]:
np.log(a)

array([[0.69314718, 1.09861229],
       [1.94591015, 2.07944154]])

In [84]:
np.exp(a)

array([[   7.3890561 ,   20.08553692],
       [1096.63315843, 2980.95798704]])

In [85]:
np.log10(a)

array([[0.30103   , 0.47712125],
       [0.84509804, 0.90308999]])

In [86]:
np.exp2(a)

array([[  4.,   8.],
       [128., 256.]])

### Random concept

In [87]:
from numpy import random

In [88]:
random.randint(100) # generate a random integer from 0 to 100

0

In [89]:
random.randint(10,100,size = 11)

array([91, 24, 89, 61, 38, 31, 14, 71, 34, 90, 16])

In [90]:
random.rand() # 0 to 1

0.4698665271527741

In [91]:
a = random.rand(10)
a

array([0.89462511, 0.5233629 , 0.04587887, 0.19888098, 0.52189625,
       0.35006595, 0.34418813, 0.56783923, 0.47919127, 0.04040289])

In [92]:
a*10

array([8.94625107, 5.23362896, 0.45878872, 1.98880983, 5.21896254,
       3.50065945, 3.44188129, 5.67839234, 4.79191266, 0.40402893])

In [93]:
a+10

array([10.89462511, 10.5233629 , 10.04587887, 10.19888098, 10.52189625,
       10.35006595, 10.34418813, 10.56783923, 10.47919127, 10.04040289])

In [94]:
a+a

array([1.78925021, 1.04672579, 0.09175774, 0.39776197, 1.04379251,
       0.70013189, 0.68837626, 1.13567847, 0.95838253, 0.08080579])

In [95]:
random.choice([3,5,12],size=(2,4))

array([[12, 12, 12, 12],
       [ 3,  3,  5, 12]])

In [96]:
random.choice([3,5,12],p=[0.2,0.1,0.7],size=(4,20))

array([[12, 12,  3, 12, 12, 12, 12,  5,  5, 12, 12, 12, 12, 12, 12, 12,
         3, 12,  5, 12],
       [12, 12, 12, 12,  3, 12,  3, 12, 12, 12, 12,  3, 12,  3, 12,  5,
        12, 12,  5, 12],
       [12,  3, 12, 12,  5, 12,  3,  3, 12,  3, 12, 12, 12, 12, 12, 12,
        12, 12,  5, 12],
       [12,  3, 12,  3, 12, 12,  3, 12, 12, 12,  5, 12, 12,  5, 12,  3,
         3,  5, 12,  3]])

In [110]:
np.linalg.eig(mat)

NameError: name 'mat' is not defined

In [2]:
import numpy as np
np.sin(90)

0.8939966636005579

In [3]:
np.arcsin(90)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in arcsin
  """Entry point for launching an IPython kernel.


nan

In [5]:
array=np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
array.argmin()

0

In [10]:
np.round(12.36)

12.0

In [14]:
round(12.51)

13